baseURL = 'https://blog.codebar.io'
locale = 'en-US'
title = 'codebar Blog'
theme = 'codebar-fresh'

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 20

  [[menus.main]]
    name = 'Tags'
    pageRef = '/tags'
    weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'

[pagination]
  pagerSize = 10

[params]
  author = 'codebar'
  description = 'A blog about codebar, diversity in tech, and our community'
